openapi: 3.0.3
info:
  title: "Final API"
  description: "Final API"
  version: "1.0.0"
servers:
  - url: "https://Final"
paths:
  /api/auth/signup:
    post:
      summary: "Register a new user"
      operationId: "registerUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        "200":
          description: "User CREATED"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
components:
  schemas:
    MessageResponse:
      type: object
      properties:
        message:
          type: string
    SignUpRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    AccessToken:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/User"
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
    RefreshToken:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/User"
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        created:
          type: string
          format: date-time
        profile:
          $ref: "#/components/schemas/Profile"
    Profile:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        user:
          $ref: "#/components/schemas/User"

