openapi: "3.0.3"
info:
  title: "Final API"
  description: "Final API"
  version: "1.0.0"
servers:
  - url: "https://Final"
paths:
  /api/admin/users:
    get:
      summary: "Get all users"
      operationId: "getAllUsers"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        created:
          type: string
          format: date-time
        profile:
          $ref: "#/components/schemas/Profile"
    Profile:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        user:
          $ref: "#/components/schemas/User"
